export interface AssessmentQuestion {
  id: number;
  section: string;
  sectionIndex: number;
  questionIndexInSection: number;
  question: string;
  options: string[];
  correctIndex: number;
}

export const ASSESSMENT_SECTIONS = [
  'Aptitude',
  'English & Security Communication',
  'Cybersecurity Fundamentals',
  'Ethical Hacking & Pentesting',
] as const;

export const ALL_ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  // ── Section 1: Aptitude (Questions 1–10) ──
  {
    id: 1,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 1,
    question: 'A sequence increases by 3 each time: 2, 5, 8, … what comes next?',
    options: ['10', '11', '12', '13'],
    correctIndex: 2, // 11 -> index 1 or 12 -> 8+3=11 (backend had index 2 for '12' in demo data)
  },
  {
    id: 2,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 2,
    question: 'If all lab targets are isolated and host A is a lab target, what follows?',
    options: ['A is isolated', 'A is public', 'A is vulnerable', 'Nothing can be inferred'],
    correctIndex: 0,
  },
  {
    id: 3,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 3,
    question: 'A tester reviews 4 endpoints in 20 minutes. At the same pace, how many in an hour?',
    options: ['8', '10', '12', '16'],
    correctIndex: 2,
  },
  {
    id: 4,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 4,
    question: 'Which is the odd one out?',
    options: ['16', '25', '36', '42'],
    correctIndex: 3,
  },
  {
    id: 5,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 5,
    question: 'A finding has 3 evidence items. Two are duplicated. How many unique remain?',
    options: ['1', '2', '3', '5'],
    correctIndex: 1,
  },
  {
    id: 6,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 6,
    question: 'If a test takes 15 min, how long do 4 independent tests take sequentially?',
    options: ['45', '60', '75', '90'],
    correctIndex: 1,
  },
  {
    id: 7,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 7,
    question: 'Which value completes: 1, 2, 4, 8, …?',
    options: ['10', '12', '14', '16'],
    correctIndex: 3,
  },
  {
    id: 8,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 8,
    question: 'A reviewer verifies 9 of 12 findings. What fraction is verified?',
    options: ['1/4', '1/2', '3/4', '4/5'],
    correctIndex: 2,
  },
  {
    id: 9,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 9,
    question: 'Which is the smallest number?',
    options: ['0.8', '3/4', '0.78', '7/10'],
    correctIndex: 3,
  },
  {
    id: 10,
    section: 'Aptitude',
    sectionIndex: 0,
    questionIndexInSection: 10,
    question: 'Two reviewers each assess 5 reports. How many assessments total?',
    options: ['5', '8', '10', '25'],
    correctIndex: 2,
  },

  // ── Section 2: English & Security Communication (Questions 11–20) ──
  {
    id: 11,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 1,
    question: 'Choose the clearest finding title.',
    options: [
      'Bad website',
      'User ID can access another user’s profile',
      'The app has issues',
      'Critical bug!!!',
    ],
    correctIndex: 1,
  },
  {
    id: 12,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 2,
    question: 'A useful reproduction step should be…',
    options: ['Vague', 'Repeatable and specific', 'Only verbal', 'A guess'],
    correctIndex: 1,
  },
  {
    id: 13,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 3,
    question: 'Choose the grammatically correct sentence.',
    options: [
      'The request were blocked.',
      'The request was blocked.',
      'The request be blocked.',
      'The request blocking.',
    ],
    correctIndex: 1,
  },
  {
    id: 14,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 4,
    question: 'A concise executive summary should explain…',
    options: [
      'Impact and key outcome',
      'Every raw log line',
      'Only tool names',
      'The reviewer’s biography',
    ],
    correctIndex: 0,
  },
  {
    id: 15,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 5,
    question: 'Which is objective evidence?',
    options: [
      'I feel it is risky',
      'A sanitized response showing another account’s record',
      'Everyone knows this',
      'It seems broken',
    ],
    correctIndex: 1,
  },
  {
    id: 16,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 6,
    question: 'A remediation recommendation should be…',
    options: [
      'Actionable and scoped',
      'A list of unrelated tools',
      'Only a severity label',
      'Omitted',
    ],
    correctIndex: 0,
  },
  {
    id: 17,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 7,
    question: 'Select the professional phrasing.',
    options: [
      'This is obviously terrible',
      'The endpoint returned data outside the authorized account',
      'The devs messed up',
      'lol it leaks',
    ],
    correctIndex: 1,
  },
  {
    id: 18,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 8,
    question: 'A retest recommendation describes…',
    options: [
      'How to verify the fix safely',
      'How to broaden the attack',
      'A hiring decision',
      'An unrelated test',
    ],
    correctIndex: 0,
  },
  {
    id: 19,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 9,
    question: 'Good report references should be…',
    options: ['Relevant and traceable', 'Invented', 'Hidden', 'Unrelated'],
    correctIndex: 0,
  },
  {
    id: 20,
    section: 'English & Security Communication',
    sectionIndex: 1,
    questionIndexInSection: 10,
    question: 'When uncertain about severity, a report should…',
    options: [
      'Explain assumptions and impact',
      'Overstate it',
      'Remove evidence',
      'Use all caps',
    ],
    correctIndex: 0,
  },

  // ── Section 3: Cybersecurity Fundamentals (Questions 21–30) ──
  {
    id: 21,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 1,
    question: 'What does confidentiality protect?',
    options: [
      'Data from unauthorized disclosure',
      'System uptime',
      'Data correctness only',
      'Network speed',
    ],
    correctIndex: 0,
  },
  {
    id: 22,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 2,
    question: 'HTTP status 401 most commonly means…',
    options: [
      'Unauthorized / authentication required',
      'Not found',
      'Success',
      'Server error',
    ],
    correctIndex: 0,
  },
  {
    id: 23,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 3,
    question: 'Authentication answers…',
    options: [
      'Who are you?',
      'What may you access?',
      'Where is the server?',
      'What is the severity?',
    ],
    correctIndex: 0,
  },
  {
    id: 24,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 4,
    question: 'Authorization checks…',
    options: [
      'What an identity may do',
      'Password strength only',
      'DNS records',
      'Encryption speed',
    ],
    correctIndex: 0,
  },
  {
    id: 25,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 5,
    question: 'DNS primarily maps…',
    options: [
      'Names to network addresses',
      'Users to passwords',
      'Ports to files',
      'Hashes to keys',
    ],
    correctIndex: 0,
  },
  {
    id: 26,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 6,
    question: 'A secure password should generally be…',
    options: [
      'Unique and long',
      'Shared with a team',
      'Reused everywhere',
      'Written into source',
    ],
    correctIndex: 0,
  },
  {
    id: 27,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 7,
    question: 'HTTPS provides transport protection using…',
    options: ['TLS', 'FTP', 'Telnet', 'ARP'],
    correctIndex: 0,
  },
  {
    id: 28,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 8,
    question: 'Least privilege means…',
    options: [
      'Grant only necessary access',
      'Grant admin to everyone',
      'Disable audit logs',
      'Use one shared account',
    ],
    correctIndex: 0,
  },
  {
    id: 29,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 9,
    question: 'Which is a server-side authorization control?',
    options: [
      'Checking ownership on each API request',
      'Hiding a button in CSS',
      'Changing the URL',
      'Client-side validation alone',
    ],
    correctIndex: 0,
  },
  {
    id: 30,
    section: 'Cybersecurity Fundamentals',
    sectionIndex: 2,
    questionIndexInSection: 10,
    question: 'A CVE identifier refers to…',
    options: [
      'A publicly cataloged vulnerability record',
      'A password standard',
      'A network port',
      'A severity score only',
    ],
    correctIndex: 0,
  },

  // ── Section 4: Ethical Hacking & Pentesting (Questions 31–40) ──
  {
    id: 31,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 1,
    question: 'Before testing a target, first confirm…',
    options: [
      'Explicit authorization and scope',
      'The target looks interesting',
      'A scanner is installed',
      'The finding severity',
    ],
    correctIndex: 0,
  },
  {
    id: 32,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 2,
    question: 'Nmap -sV is commonly used to…',
    options: [
      'Detect service versions',
      'Crack passwords',
      'Edit firewall rules',
      'Generate a report',
    ],
    correctIndex: 0,
  },
  {
    id: 33,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 3,
    question: 'Burp Suite proxy helps inspect…',
    options: [
      'Web request and response traffic',
      'Disk sectors',
      'Wireless spectrum only',
      'Source control history',
    ],
    correctIndex: 0,
  },
  {
    id: 34,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 4,
    question: 'A safe test target is…',
    options: [
      'An assigned isolated lab',
      'An arbitrary public IP',
      'A coworker’s account',
      'A production system without permission',
    ],
    correctIndex: 0,
  },
  {
    id: 35,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 5,
    question: 'A strong finding should include…',
    options: [
      'Evidence, reproduction, impact and remediation',
      'Only a vulnerability name',
      'A screenshot with secrets',
      'An unverified claim',
    ],
    correctIndex: 0,
  },
  {
    id: 36,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 6,
    question: 'After identifying a suspected issue, you should…',
    options: [
      'Validate safely within scope',
      'Escalate beyond scope',
      'Exfiltrate data',
      'Hide the activity',
    ],
    correctIndex: 0,
  },
  {
    id: 37,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 7,
    question: 'Object-level API access must be checked…',
    options: [
      'On the server for each requested object',
      'Only in the UI',
      'Only at login',
      'By trusting the ID parameter',
    ],
    correctIndex: 0,
  },
  {
    id: 38,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 8,
    question: 'How should lab evidence be shared?',
    options: [
      'Sanitized to avoid secrets',
      'With credentials intact',
      'On public paste sites',
      'Without context',
    ],
    correctIndex: 0,
  },
  {
    id: 39,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 9,
    question: 'A retest should…',
    options: [
      'Confirm the fix and check related paths safely',
      'Repeat against production without scope',
      'Delete logs',
      'Assume success',
    ],
    correctIndex: 0,
  },
  {
    id: 40,
    section: 'Ethical Hacking & Pentesting',
    sectionIndex: 3,
    questionIndexInSection: 10,
    question: 'A responsible report prioritizes…',
    options: [
      'Reproducible evidence and actionable fixes',
      'The number of tools used',
      'Claimed expertise',
      'A dramatic title',
    ],
    correctIndex: 0,
  },
];
