export interface ToolItem {
  id: string;
  name: string;
  category: 'Recon & Discovery' | 'Web & API' | 'Vulnerability & Exploitation' | 'Password & Crypto' | 'Traffic & Forensics';
  tagline: string;
  syntax: string;
  description: string;
  keyFlags: string;
  claimedBy: string;
}

export const TOOLBOX_CATEGORIES = [
  'All',
  'Recon & Discovery',
  'Web & API',
  'Vulnerability & Exploitation',
  'Password & Crypto',
  'Traffic & Forensics',
] as const;

export const TOOLBOX_TOOLS: ToolItem[] = [
  {
    id: 'nmap',
    name: 'Nmap',
    category: 'Recon & Discovery',
    tagline: 'Network Scanning & Service Discovery',
    syntax: 'nmap -sC -sV -p- -T4 -oN nmap_report.txt <LAB_TARGET>',
    description: 'Perform full 65,535 TCP port discovery with standard NSE scripts and service version detection against authorized hosts.',
    keyFlags: '-sC (default scripts) · -sV (service versions) · -p- (all ports) · -T4 (speed)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'curl',
    name: 'cURL',
    category: 'Web & API',
    tagline: 'HTTP Inspection & API Testing',
    syntax: 'curl -i -X POST <LAB_URL>/api/auth -H "Authorization: Bearer <TOKEN>" -H "Content-Type: application/json" -d \'{"role":"admin"}\'',
    description: 'Inspect raw HTTP response headers, send custom HTTP methods, headers, and JSON payloads to test API endpoints and authorization boundaries.',
    keyFlags: '-i (include headers) · -X (method) · -H (headers) · -d (POST payload) · -k (insecure TLS)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'burp',
    name: 'Burp Suite',
    category: 'Web & API',
    tagline: 'Web Application Security Proxy',
    syntax: '127.0.0.1:8080 (Proxy) -> Target -> Intercept -> Repeater (Ctrl+R)',
    description: 'Route and manipulate HTTP traffic in flight, test IDOR boundaries, tamper session cookies, and replay modified requests in Repeater.',
    keyFlags: 'HTTP/HTTPS Proxy · Repeater · Intruder Fuzzing · Match/Replace Rules · WebSocket Inspector',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'ffuf',
    name: 'ffuf',
    category: 'Web & API',
    tagline: 'High-Speed Web Fuzzer',
    syntax: 'ffuf -u <LAB_URL>/FUZZ -w /wordlists/common.txt -mc 200,301,302,403 -c -v',
    description: 'High-concurrency Go web fuzzer for directory brute-forcing, parameter discovery, HTTP method fuzzing, and virtual host enumeration.',
    keyFlags: '-u (target URL) · -w (wordlist) · -mc (match status codes) · -fc (filter codes) · -c (colorize)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'gobuster',
    name: 'Gobuster',
    category: 'Recon & Discovery',
    tagline: 'Directory & DNS Brute-Forcer',
    syntax: 'gobuster dir -u <LAB_URL> -w /wordlists/dirb/big.txt -x php,html,js,json -t 30',
    description: 'High-performance directory, file, DNS subdomain, and vhost brute-forcer designed for rapid reconnaissance workflows.',
    keyFlags: 'dir (directory mode) · dns (subdomain mode) · -x (file extensions) · -t (threads)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'sqlmap',
    name: 'SQLmap',
    category: 'Vulnerability & Exploitation',
    tagline: 'Automated SQL Injection & Takeover',
    syntax: 'sqlmap -u "<LAB_URL>/item?id=1" --dbs --batch --risk=2 --level=2 --random-agent',
    description: 'Automated detection and exploitation of SQL injection flaws, database fingerprinting, schema dumping, and data extraction.',
    keyFlags: '--dbs (enumerate DBs) · --tables (list tables) · --dump (extract data) · --batch (auto-yes)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'hydra',
    name: 'Hydra',
    category: 'Password & Crypto',
    tagline: 'Parallelized Network Login Cracker',
    syntax: 'hydra -l admin -P /wordlists/rockyou.txt <LAB_TARGET> ssh -t 4 -V',
    description: 'High-speed parallelized network login auditing tool supporting SSH, FTP, HTTP-POST-FORM, SMB, RDP, and MySQL authentication checks.',
    keyFlags: '-l (user) / -L (user list) · -P (password list) · -t (concurrent tasks) · -s (port)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'john',
    name: 'John the Ripper',
    category: 'Password & Crypto',
    tagline: 'Fast Offline Password Hash Cracker',
    syntax: 'john --wordlist=/wordlists/rockyou.txt --format=raw-sha256 hashes.txt',
    description: 'Offline password recovery tool with automatic hash format identification, custom rule mangling, and high-performance dictionary modes.',
    keyFlags: '--wordlist (dictionary) · --format (hash type) · --rules (mangling) · --show (view cracked)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'hashcat',
    name: 'Hashcat',
    category: 'Password & Crypto',
    tagline: 'GPU-Accelerated Hash Recovery',
    syntax: 'hashcat -m 1000 -a 0 ntlm_hashes.txt /wordlists/rockyou.txt -r rules/best64.rule -O',
    description: 'World’s fastest GPU-based rule, mask, and dictionary hash recovery utility supporting hundreds of cryptographic hashing algorithms.',
    keyFlags: '-m 1000 (NTLM) / 0 (MD5) / 1800 (SHA512) · -a 0 (straight) / 3 (mask) · -O (optimized)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'wireshark',
    name: 'Wireshark / TShark',
    category: 'Traffic & Forensics',
    tagline: 'Packet Capture & Protocol Dissector',
    syntax: 'tshark -i eth0 -Y "http.request.method == \'POST\' || dns" -T fields -e ip.src -e ip.dst -e http.host',
    description: 'Deep protocol packet dissection, live traffic capture, TLS stream analysis with RSA keys, and fine-grained packet filtering.',
    keyFlags: '-i (interface) · -Y (display filter) · -T fields (field projection) · -w (save PCAP)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'metasploit',
    name: 'Metasploit Framework',
    category: 'Vulnerability & Exploitation',
    tagline: 'Exploit Verification & Testing Suite',
    syntax: 'msfconsole -q -x "use exploit/multi/handler; set LHOST <IP>; set LPORT 4444; run"',
    description: 'Modular penetration testing platform used for verifying the exploitability of verified CVEs and managing interactive test sessions.',
    keyFlags: 'use <module> · set RHOSTS <target> · check (safe verify) · exploit · sessions -l',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'nikto',
    name: 'Nikto',
    category: 'Web & API',
    tagline: 'Web Server Vulnerability Scanner',
    syntax: 'nikto -h <LAB_URL> -Tuning 1,2,3,b -C all -output nikto_report.html',
    description: 'Scans web servers for dangerous files, outdated server packages, known misconfigurations, and outdated HTTP headers.',
    keyFlags: '-h (host/URL) · -Tuning (scan categories) · -C (all ports) · -output (save report)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'whatweb',
    name: 'WhatWeb',
    category: 'Recon & Discovery',
    tagline: 'Next-Gen Web Fingerprinter',
    syntax: 'whatweb -a 3 <LAB_URL> --log-json=whatweb_results.json',
    description: 'Identifies web technologies, CMS platforms, JavaScript libraries, server frameworks, and embedded headers with high accuracy.',
    keyFlags: '-a 1 (stealthy) / 3 (aggressive) · -v (verbose) · --log-json (structured export)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'netcat',
    name: 'Netcat (nc)',
    category: 'Recon & Discovery',
    tagline: 'Networking Swiss Army Knife',
    syntax: 'nc -nvlp 4444  # listener | nc -nv <LAB_TARGET> 80  # banner grab',
    description: 'Versatile raw socket utility for reading/writing data across network connections, port inspection, banner grabbing, and listeners.',
    keyFlags: '-l (listen mode) · -v (verbose) · -n (numeric IPs only) · -p (port) · -u (UDP mode)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'tcpdump',
    name: 'tcpdump',
    category: 'Traffic & Forensics',
    tagline: 'Command-Line Packet Analyzer',
    syntax: 'tcpdump -nn -i eth0 "tcp[tcpflags] & (tcp-syn) != 0 and port 80" -c 50',
    description: 'Lightweight CLI packet capture engine for capturing SYN/ACK handshakes, inspecting DNS queries, and generating PCAP evidence.',
    keyFlags: '-nn (no hostname/port resolution) · -i (interface) · -w (write to file) · -c (count)',
    claimedBy: 'CLAIMED',
  },
  {
    id: 'ghidra',
    name: 'Ghidra',
    category: 'Vulnerability & Exploitation',
    tagline: 'Binary Analysis & Reverse Engineering',
    syntax: 'ghidraRun  # Headless: analyzeHeadless <PROJECT_DIR> <PROJECT> -import <BINARY>',
    description: 'NSA software reverse engineering framework featuring a high-fidelity decompiler for x86, ARM, MIPS, and control flow graph inspection.',
    keyFlags: 'C Decompiler · Disassembler · Control Flow Graphs · Symbol Tree · Memory Map',
    claimedBy: 'CLAIMED',
  },
];
